### ISSUE TITLE
Code for Stage 1

### ISSUE THREAD

**Issue by zhuyi-scnu** [Upper9527/GeReA#1]
Is the code for "Stage 1: Question-Aware Prompt Caption Generation"  not in the project?  I don't quite understand the details of this stage.

**Comment by Upper9527** [comment]
Don't worry, I will upload the Stage 1 code after the ICLR deadline. You can continue your research using the processed captions.

**Comment by Upper9527** [comment]
Hi, the code for generating captions has been uploaded to the generate_captions folder. Before running the code, you need to install the dependencies for Instrucblip. Then, move the img2prompt_vqa.py file to the ./LAVIS-main/lavis/models/img2prompt_models/ directory. Finally, run the generate_question_aware_prompt_captions_from_instructblip.py script to obtain the captions. If you have any questions, feel free to contact me.
