### ISSUE TITLE
How to generate Question-Aware Prompt Caption

### ISSUE THREAD

**Issue by AlexandreWANG915** [Upper9527/GeReA#2]
Hello! Thanks for sharing such excellent work. I have gone through the project and didn't find the code related to Question-Aware Prompt Caption Generation. Could you update the code for this part? Thanks!

**Comment by Upper9527** [comment]
Hi, the code for generating captions has been uploaded to the generate_captions folder. Before running the code, you need to install the dependencies for Instrucblip. Then, move the img2prompt_vqa.py file to the ./LAVIS-main/lavis/models/img2prompt_models/ directory. Finally, run the generate_question_aware_prompt_captions_from_instructblip.py script to obtain the captions. If you have any questions, feel free to contact me.
